### ISSUE TITLE
initial password location?

### ISSUE THREAD

**Issue by n1ete** [RuimteDraak/hassio-etesync-server#1]
just discovered this yesterdy and wanna say thanks! 
couldnt find the initial generated password, where can i find that one?

**Comment by RuimteDraak** [comment]
The first time the plugin is started a password is generated and shown in the logs. If that log is lost, your best option is to uninstall and do a fresh install and keep and eye on the log the first time the plugin starts.

**Comment by n1ete** [comment]
thanks that helped!
